-- 코드를 작성해주세요
SELECT ID, 
CASE WHEN A.GROUP_NUM=1 THEN 'CRITICAL' WHEN A.GROUP_NUM=2 THEN 'HIGH' WHEN A.GROUP_NUM=3 THEN 'MEDIUM' WHEN A.GROUP_NUM=4 THEN 'LOW' END AS COLONY_NAME 
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS GROUP_NUM FROM ECOLI_DATA) A 
ORDER BY ID;