SELECT 
u.USER_ID AS USER_ID, 
u.NICKNAME AS NICKNAME, 
CONCAT_WS(' ', u.CITY, u.STREET_ADDRESS1, u.STREET_ADDRESS2) AS '전체주소', 
CONCAT_WS('-', LEFT(u.TLNO, 3), SUBSTRING(u.TLNO, 4, 4), RIGHT(u.TLNO, 4)) AS '전화번호' 
FROM USED_GOODS_USER u 
JOIN 
(SELECT WRITER_ID 
FROM USED_GOODS_BOARD 
GROUP BY WRITER_ID 
HAVING COUNT(*) >= 3) w 
ON u.USER_ID = w.WRITER_ID 
ORDER BY USER_ID DESC;