-- 코드를 작성해주세요
SELECT B.YEAR AS YEAR, (B.MAX_SIZE-A.SIZE_OF_COLONY) AS YEAR_DEV, ID 
FROM ECOLI_DATA A
JOIN 
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE 
FROM ECOLI_DATA 
GROUP BY YEAR(DIFFERENTIATION_DATE)) B 
WHERE YEAR(DIFFERENTIATION_DATE) = B.YEAR 
ORDER BY YEAR, YEAR_DEV;
