-- 코드를 입력하세요
SELECT A.FLAVOR 
FROM ICECREAM_INFO A JOIN 
(SELECT FLAVOR, TOTAL_ORDER 
FROM FIRST_HALF 
WHERE TOTAL_ORDER > 3000) AS B
WHERE A.FLAVOR = B.FLAVOR AND A.INGREDIENT_TYPE = 'fruit_based' 
ORDER BY B.TOTAL_ORDER DESC;