-- 코드를 작성해주세요
SELECT B.ID AS ID, A.FISH_NAME AS FISH_NAME, B.LENGTH AS LENGTH 
FROM FISH_NAME_INFO A 
JOIN 
(SELECT ID, FISH_TYPE, LENGTH 
FROM FISH_INFO 
WHERE (FISH_TYPE, LENGTH) IN 
(SELECT FISH_TYPE, MAX(LENGTH) 
FROM FISH_INFO 
GROUP BY FISH_TYPE)) B 
WHERE A.FISH_TYPE = B.FISH_TYPE 
ORDER BY ID;