SELECT 
s.SCORE AS SCORE, 
e.EMP_NO AS EMP_NO, 
e.EMP_NAME AS EMP_NAME, 
e.POSITION AS POSITION, 
e.EMAIL AS EMAIL 
FROM HR_EMPLOYEES AS e
JOIN 
(SELECT EMP_NO, SUM(SCORE) AS SCORE FROM HR_GRADE 
GROUP BY EMP_NO 
HAVING SUM(SCORE) = (SELECT SUM(SCORE) OVER (PARTITION BY EMP_NO) AS MAX_SCORE FROM HR_GRADE 
ORDER BY MAX_SCORE DESC LIMIT 1)) AS s 
ON e.EMP_NO = s.EMP_NO;
