-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, A.REPLY_ID, A.WRITER_ID, A.CONTENTS, DATE_FORMAT(A.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE 
FROM USED_GOODS_REPLY A JOIN (SELECT * 
FROM USED_GOODS_BOARD 
WHERE MONTH(CREATED_DATE) = 10) B 
ON A.BOARD_ID = B.BOARD_ID 
ORDER BY A.CREATED_DATE ASC, B.TITLE ASC;
