SELECT 
d.DEPT_ID AS DEPT_ID, 
d.DEPT_NAME_EN AS DEPT_NAME_EN,
s.AVG_SAL AS AVG_SAL 
FROM HR_DEPARTMENT d 
JOIN 
(SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL 
FROM HR_EMPLOYEES 
GROUP BY DEPT_ID) s 
WHERE d.DEPT_ID = s.DEPT_ID 
ORDER BY AVG_SAL DESC;