SELECT a.FISH_COUNT AS FISH_COUNT, a.MAX_LENGTH AS MAX_LENGTH, a.FISH_TYPE AS FISH_TYPE 
FROM 
(SELECT 
AVG(COALESCE(LENGTH, 10)) AS AVG_LENGTH, 
COUNT(*) AS FISH_COUNT, 
MAX(LENGTH) AS MAX_LENGTH, 
FISH_TYPE
FROM FISH_INFO 
GROUP BY FISH_TYPE) AS a
WHERE a.AVG_LENGTH >= 33
ORDER BY FISH_TYPE;